# Generated by Django 3.2.25 on 2025-07-22 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formation', models.CharField(max_length=15)),
                ('fairy', models.CharField(max_length=15)),
                ('speed', models.PositiveSmallIntegerField(default=4)),
                ('has_HG', models.BooleanField(default=False)),
                ('tank', models.CharField(max_length=15)),
                ('has_armor', models.BooleanField(default=True)),
                ('DPS', models.CharField(max_length=30)),
                ('has_chip', models.BooleanField(default=True)),
                ('max_HP', models.PositiveSmallIntegerField()),
                ('damage', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
